name: Publicar Noticias

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script
        run: python main.py

      - name: Commit y push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add noticias/*.json
          git commit -m "nueva noticia" || echo "Sin cambios"
          git push https://cdiaz21:${{ secrets.GH_TOKEN }}@github.com/cdiaz21/Noticias_Lagranverdad.git
