name: Publicar Noticia

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install torch requests beautifulsoup4 transformers

      - name: Run script
        run: python main.py

      - name: Commit y push de noticias
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add noticias/
          git commit -m "nueva noticia" || echo "Sin cambios"
          git push
