name: Generar y publicar noticias

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'  # Cada 4 horas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
          BLOGGER_CREDENTIALS_JSON_BASE64: ${{ secrets.BLOGGER_CREDENTIALS_JSON_BASE64 }}
          BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}

      - name: Confirmación final
        run: echo "¡Proceso de noticias completado correctamente!"
