name: Generar Noticias

on:
  push:
  schedule:
    - cron: '0 9 * * *'  # Todos los días a las 9 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script
        run: python main.py

      - name: Subir archivos generados
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add noticias/
          git commit -m "Noticias del día $(date +'%Y-%m-%d')" || echo "Sin cambios"
          git push
