name: Generar y publicar noticias

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'  # Ejecuta diariamente a las 9:00 AM UTC

jobs:
  publicar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    - name: Crear archivo de credenciales de Blogger
      run: |
        echo "${{ secrets.BLOGGER_CREDENTIALS_BASE64 }}" | base64 -d > blogger_credentials.json

    - name: Ejecutar script principal
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
        BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
        BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
      run: python main.py
