name: Generar y publicar noticias

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'  # Cada 4 horas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install torch

      - name: Ejecutar script principal
        run: python main.py

      - name: Confirmación final
        run: echo "¡Proceso de noticias completado correctamente!"
