name: Generar y publicar noticias

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Ejecutar todos los días a las 12:00 UTC

jobs:
  generar_y_publicar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script principal
        run: python main.py

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Hacer commit y push si hay cambios
        run: |
          git add noticias/*.json
          git diff --cached --quiet || git commit -m "nueva noticia"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
